# Generated by Django 6.0.3 on 2026-04-16 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_tasks_completed_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtasks',
            options={'verbose_name_plural': 'Подзадачи'},
        ),
        migrations.AlterModelOptions(
            name='taskhistory',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Истории задач'},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Задачи'},
        ),
    ]
