# Generated by Django 6.0.3 on 2026-03-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_subtasks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="priority",
            field=models.CharField(
                choices=[(1, "НИЗКИЙ"), (2, "СРЕДНИЙ"), (3, "ВЫСОКИЙ")],
                default=2,
                max_length=1,
                verbose_name="Приоритет",
            ),
        ),
    ]
