# Generated by Django 6.0.3 on 2026-04-16 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_subtasks_options_alter_taskhistory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistory',
            name='action',
            field=models.CharField(choices=[('created', 'Создана'), ('updated', 'Обновлена'), ('deleted', 'Удалена'), ('toggled', 'Переключен статус')], default='created', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_history_entries', to=settings.AUTH_USER_MODEL, verbose_name='Кем изменено'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время и дата'),
        ),
    ]
