# Generated by Django 6.0.3 on 2026-03-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_alter_tasks_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="priority",
            field=models.CharField(
                choices=[("L", "НИЗКИЙ"), ("M", "СРЕДНИЙ"), ("H", "ВЫСОКИЙ")],
                default="M",
                max_length=1,
                verbose_name="Приоритет",
            ),
        ),
    ]
