# Generated by Django 6.0.3 on 2026-04-02 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0005_taskhistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taskhistory",
            options={"ordering": ["-timestamp"]},
        ),
    ]
