"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-hq@+i3(zo3csnbtt-!zn)8eji63l$k=i=pm3a-6l=grbry6h9-"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework',
    'debug_toolbar',
    'drf_spectacular',
    'drf_spectacular_sidecar',
    
    'todo',
    'users',
    'api',
]

MIDDLEWARE = [
    #Порядок тут важен!!! Пример: Сессия должна быть раньше аутентификации ьк аунтефикация использует сессии
                    # REDIS
    # """Эти middleware автоматически сохраняют готовую HTML-страницу в Redis, когда пользователь её открывает.
    #   При следующем запросе страница отдаётся из Redis, минуя Django (вьюха, шаблоны, БД)."""
    # 'django.middleware.cache.UpdateCacheMiddleware', # Мидлвэр для кэша(редис) ПЕРВЫЙ, ЧТОБ УВПЕВАЛ СОХРАНЯТЬ ВСЕ
    # """"""
    "django.middleware.security.SecurityMiddleware", #Заставляет праузер общаться с нашим сайтом только по Https
    "django.contrib.sessions.middleware.SessionMiddleware", #управляет сессиями
    "django.middleware.common.CommonMiddleware", #делает сайт удобнее (Авто-слеши вконце или www к адрессу)
    "django.middleware.csrf.CsrfViewMiddleware", #защита от CSRF
    "django.contrib.auth.middleware.AuthenticationMiddleware", #request.user
    "django.contrib.messages.middleware.MessageMiddleware", # Флэш сообщения
    "django.middleware.clickjacking.XFrameOptionsMiddleware", #Защита от Clickjacking(от злоумышленников)
    
    # 'debug_toolbar.middleware.DebugToolbarMiddleware', #Дэбагер    
    # # Castom middleware
    
    'todo.middleware.RequestLogMiddleware',

    # #Тоже редис мидлвер ПОСЛЕДНИЙ ЧТОБ МОГ ПЕРЕХВАТИТЬ ЗАПРОС ДО ТОГО, КАК ОСТАЛЬНЫЕ НАЧНУТ РАБОТУ
    # 'django.middleware.cache.FetchFromCacheMiddleware',
]
# CACHE_MIDDLEWARE_SECONDS = 60  # кэшировать на 60 секунд СТРАНИЦУ HTML
# CACHE_MIDDLEWARE_KEY_PREFIX = 'todoapp' # ПРЕФИКС ДЛЯ КЛЮЧА НА СЛУЧАЙ НЕСКОЛЬКИХ ПРОЕКТОВ

"""      НЕ КЭШИРУЕМ СТРАНИЦЫ, ТК ОНИ ПЕРСОНАЛИЗИРОВАНЫ (КАЖДЫЙ ВИДИТ СВОИ ЗАДАЧИ)                  """

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
import os

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_NAME', 'tododb'),
        'USER': os.environ.get('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'postgres'),
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
        'PORT': os.environ.get('POSTGRES_PORT', 5432),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"


LOGIN_REDIRECT_URL = 'tasks_list'
LOGOUT_REDIRECT_URL = 'home'

CSRF_TRUSTED_ORIGINS = [
    'https://*.github.dev',
    'https://*.githubpreview.dev',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = 'None'
CSRF_COOKIE_SECURE = True

REST_FRAMEWORK = {
    # Документация апи Без этой строки DRF не будет знать о drf-spectacular
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',      # для браузера
        'rest_framework_simplejwt.authentication.JWTAuthentication', # для токенов
    ],

    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 5
}
    # Настройки документации
SPECTACULAR_SETTINGS = {
    'TITLE': 'Мой ToDo App API',
    'DESCRIPTION': 'API для управления задачами, категориями и подзадачами',
    'VERSION': '1.0.0',
    # уменьшает размер страницы(не включает штмл)
    'SERVE_INCLUDE_SCHEMA': False,
    # для работы без интернета
    'SWAGGER_UI_DIST': 'SIDECAR',
    'SWAGGER_UI_FAVICON_HREF': 'SIDECAR',
}

#Настройка для ONA
import socket
hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
INTERNAL_IPS = [ip[: ip.rfind(".")] + ".1" for ip in ips] + ["127.0.0.1", "10.0.0.1"]
# Дебаггер
DEBUG_TOOLBAR_CONFIG = {
    "SHOW_TOOLBAR_CALLBACK": lambda request: DEBUG,
}


CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://redis:6379/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}